#!/bin/bash
echo "=== 重新初始化链 ==="
echo ""
echo "⚠️  警告：这会清除链上所有数据！"
echo ""
echo "步骤："
echo "1. 停止当前运行的 geth"
echo "2. 备份链数据（可选）"
echo "3. 重新初始化链"
echo "4. 重新启动链"
echo ""
echo "执行命令："
echo "pkill -f 'geth.*myblockchain'"
echo "cd /home/zxx/Config/blockchain/consortium_blockchain"
echo "geth --datadir ./myblockchain init genesis.json"
echo ""
echo "然后重新启动链（使用你之前的启动命令）"
