"""配置模块"""
# 导入所有配置模块
from .experiment_config import *
from .llm_config import *
from .system_config import *

__all__ = [
    # 实验配置
    "ATTACK_MODE",
    "RUN_ID",
    "RESULT_DIR",
    "TX_DIR",
    "TX_DIR_FOR_ATTACK",
    "TX_DIR_FOR_NORMAL",
    "STATIC_DATA_DIR",
    "STATIC_DATA_FILE",
    "AUDITOR_STATS_FILE",
    "COMMITTEE_VOTE_STATS_FILE",
    "PRECISION_FILE",
    "REFERENCE_SAMPLES_DIR",
    "REFERENCE_ILLEGAL_FILE",
    "REFERENCE_LEGITIMATE_FILE",
    # LLM配置
    "LLM_API_KEY",
    "LLM_BASE_URL",
    "LLM_MODEL",
    "LLM_TIMEOUT",
    "LLM_MAX_RETRIES",
    "LLM_TEMPERATURE_DEFAULT",
    "LLM_TEMPERATURE_STRATEGY",
    "LLM_TEMPERATURE_MONITOR",
    "LLM_MAX_ATTEMPTS",
    "LLM_SLEEP_TIME",
    # 系统配置
    "ALLOWED_AMOUNTS",
    "NUM_LEGIT_COMMITTEES",
    "NUM_ILLEGAL_COMMITTEES",
    "COMMITTEE_SELECT_COUNT",
    "COMMITTEE_INITIAL_WEIGHT",
    "NUM_RETAIL_USERS",
    "NUM_EXCHANGE_USERS",
    "NUM_ATTACK_USERS",
    "NUM_SMALL_TASK_ATTACKERS",
    "NUM_LARGE_TASK_ATTACKERS",
    "SMALL_TASK_AMOUNT",
    "LARGE_TASK_AMOUNT",
    "TASK_TIME_LEFT",
    "ETH_ADDRESS_FILE",
    "ETH_ADDRESS_TRAIN_FILE",
    "IF_CONTAMINATION",
    "IF_RANDOM_STATE",
    "AUDIT_INTERVAL",
    "REFERENCE_SAMPLE_COLLECTION_TIME",
    "RECENT_TRANSACTION_COUNT",
    "FAILURE_ANALYSIS_LOOKBACK",
    "CORRUPT_VOTE_THRESHOLD",
]